# Generated by Django 5.2.4 on 2025-07-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('whatsapp', models.CharField(max_length=255)),
                ('telegram', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-created_at', 'order']},
        ),
    ]
