# Generated by Django 5.2.4 on 2025-07-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teammember_created_at_teammember_experience_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
