# Generated by Django 5.0.6 on 2024-11-07 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_post_published_post_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 8, 26, 57, 328828, tzinfo=datetime.timezone.utc)),
        ),
    ]
