# Generated by Django 5.0.6 on 2024-11-07 12:52

import datetime
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_author_alter_post_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('publishes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 12, 52, 26, 216783, tzinfo=datetime.timezone.utc)),
        ),
    ]
