# Generated by Django 5.0.6 on 2024-11-07 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_managers_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 12, 58, 37, 728606, tzinfo=datetime.timezone.utc)),
        ),
    ]
