# Generated by Django 5.2.4 on 2025-09-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Under Construction', 'Construction'), ('Design', 'Design')], default='Design', max_length=30),
        ),
    ]
