module.exports = {
  content: [
    './templates/**/*.html',
    './**/templates/**/*.html',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#721616',
        secondary: '#1a365d',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
    }
  },
  plugins: [],
  
}
// This file is auto-generated by the Adyam Engine. Do not edit manually.
// If you need to make changes, please do so in the appropriate source files.
// This ensures that your changes are preserved during updates and deployments.
// For more information, visit https://adyam.engineering.com/docs   
// or contact support